---
title: "2. Estimates and ggplot2"
author: "jsg"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y %H:%M')`"
output:
  html_document:
    toc: true
    toc_float: true
    keep_md: true
    self_contained: true
---

Before doing this, review the **Estimation and Probability** lecture set slides from 
https://sites.google.com/view/biostats/lessons/estimation-and-probablity and
the  **2_estimation_lecture.R** script in the lecture_files folder of the
[CUNY-BioStats github repository](https://github.com/jsgosnell/CUNY-BioStats).


Remember you should

* add code chunks by clicking the *Insert Chunk* button on the toolbar or by
pressing *Ctrl+Alt+I* to answer the questions!
* **knit** your file to produce a markdown version that you can see!
* save your work often 
  * **commit** it via git!
  * **push** updates to github

## Using ggplot2
Let’s return to the mammal sleep dataset that we left off with last week. 
Load the dataset
```{r}
sleep <- read.csv("https://raw.githubusercontent.com/jsgosnell/CUNY-BioStats/master/datasets/sleep.csv", stringsAsFactors = T)
#need to use stringsAsFactors to make characters read in as factors
```
Last time you used the built-in plot functions to do some plots. Let’s replace 
those with ggplot2 and do some more.

1. First plot how TotalSleep is explained by BrainWt (remember the issues with 
the data).  Use ggplot2 to plot the relationship.

2. Next color code each plot point by whether or not its a primate.  In order 
to do this you can use the Primate column or (following class code) make a new 
column called Taxa to represent the information (hint:search for “ revalue”). 
Make sure axes are well-labeled.

3. Let’s work with histograms.
* What type of variation do we see in total time spent sleeping? Create a 
histogram to explore this issue.
* Facet the graph you created based on whether or not the animal is a primate 
(Primate column).
* Now only graph the data for primates.

4. Develop a properly-labeled bar graph with error bars to explore how total 
sleep changes with 
* Primate (relabeled as yes/no as Primate/Non-Primate; note 
there are multiple ways to do this!) – use a 95% confidence interval for the bar
* Predation risk (as a factor!) – use 1 standard error for the bar. Note the difference!

## Estimates and Certainty Concepts

5. What does a 95% confidence interval mean?

6. To make sure you understand the ideas of sampling, confidence intervals, and the central limit theorem, review the visualizations produced by UBC @ http://www.zoology.ubc.ca/~whitlock/Kingfisher/CLT.htm.  

7. For this question you'll need the 
central_limit_theorem.R script from the 
[code_examples folder](https://github.com/jsgosnell/CUNY-BioStats/tree/master/code_examples).

To show you how well the central limit theorem (and functions) works, you can also examine 6
distributions that display traits we described at the beginning of lab using the
central_limit_theorem.R script from the Examples folder on github (or download here);
you may need to download the VGAM package.  Source it and and then use Rstudio to review the plots
it produces. Decide what characteristics (truncation, skewness, kurtosis, sample size) speed vs.
slow the convergence of the sample mean upon normality.  The reviewed distributions are:

* Normal(Z) (0,1)  {no Kurtosis / no skewness / no truncation}
* Double exponential (0,2) {high Kurtosis / no skewness / no truncation}
* Uniform(0,1) {moderate Kurtosis / no skewness / double truncation}
* Exponential(1,1)  {high asymmetric Kurtosis / high skewness / single truncation} 
* Chi-square(df=4) {low Kurtosis / moderate skewness / single truncation} 
* Binomial distribution (p=.7) {discrete distribution]

For this question, its easiest to just source the main file and see what happens.
When you source a script, it is run in R without showing any console output
(but graphs and objects are still produced!).  Try 
`source("https://raw.githubusercontent.com/jsgosnell/CUNY-BioStats/master/code_examples/central_limit_theorem.R")`.  
You'll also need to have the VGAM library installed.